version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-26-alpha

    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout

      - run:
          name: Setup environment keys
          command: |
            echo $BANJEN_GOOGLE_SERVICES > google-services.base64
            base64 -d google-services.base64 > app/google-services.json

      - run:
          name: Instal Dependencies
          command: bash scripts/install-dependencies.sh

      - run:
          name: Build
          command: ./gradlew build -PdisablePreDex --stacktrace --console=plain

      - store_artifacts:
          path: app/build/outputs
      - store_artifacts:
          path: app/build/spoon
      - store_artifacts:
          path: app/build/reports
          destination: reports